version: '3.8'

services:

  admin-app:
    build: .
    container_name: ADMIN-PHP-FPM
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
    networks:
      - default         # Jaringan internal untuk ngobrol sama Nginx
      - shared_network  # Jaringan eksternal untuk ngobrol sama mysql_db

  admin-nginx:
    image: nginx:latest
    container_name: ADMIN-NGINX
    ports:
      - "7892:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html
    depends_on:
      - admin-app
    restart: unless-stopped
    networks:
      - default         # Nginx cukup di default saja

# Bagian Kunci: Mengambil network yang sudah dibuat oleh Docker MySQL
networks:
  shared_network:
    external: true